<?php
$z[0]=Array("click","",116,130);
$z[1]=Array("click","",174,188);
$z[2]=Array("arcurl","",363,378);
$z[3]=Array("title","",387,401);
$z[4]=Array("title","",420,434);
$z[5]=Array("description","",695,715);
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<ul class='threadlist_media j_threadlist_media'><li><div class='vpic_wrap'><img src='{@me['litpic']}' class='threadlist_pic j_m_pic ' /></div><div class='threadlist_pic_highlight j_m_pic_light'></div></li></ul>\"); ",726,1030);
$z[6][4]['runphp']="yes";
$z[7]=Array("writer","",1164,1179);
$z[8]=Array("pubdate","",1214,1259);
$z[8][4]['function']="MyDate('m-d',@me)";

?>