<?php
$z[0]=Array("click","",116,130);
$z[1]=Array("click","",174,188);
$z[2]=Array("arcurl","",363,378);
$z[3]=Array("title","",387,401);
$z[4]=Array("title","",420,434);
$z[5]=Array("description","",695,715);
$z[6]=Array("litpic","",832,847);
$z[7]=Array("litpic","",859,874);
$z[8]=Array("litpic","",883,898);
$z[9]=Array("writer","",1160,1175);
$z[10]=Array("pubdate","",1210,1255);
$z[10][4]['function']="MyDate('m-d',@me)";

?>