<li class="j_thread_list" class="j_thread_list"><div class="threadlist_li_left j_threadlist_li_left">
	<div title="[field:click/]次阅读" class="threadlist_rep_num j_rp_num">[field:click/]</div>
</div>
<div class="threadlist_li_right">
	<div class="threadlist_lz clearfix">
		<div class="threadlist_text threadlist_title j_th_tit  notStarList ">
			<a href="[field:arcurl/]" title="[field:title/]" class="j_th_tit">[field:title/]</a>
			</span>
			
		</div>
		<div class="threadlist_author" title="主题作者">
			<span class="tb_icon_author ">[field:writer/]</span>
		</div>
	</div>
	<div class="threadlist_detailclearfix">	
		<div class="threadlist_text">
			<div class="threadlist_abs threadlist_abs_onlyline">[field:description/]...</div>
			<ul class="threadlist_media j_threadlist_media" id="fm2126307861"><li><div class="vpic_wrap"><img src="[field:litpic/]" original="[field:litpic/]"  bpic="[field:litpic/]" class="threadlist_pic j_m_pic " loadprc="next" /></div><div class="threadlist_pic_highlight j_m_pic_light"></div></li></ul>

			
		</div>
		<div class="threadlist_author">
                        <span class="tb_icon_author_rely j_replyer" title="最后回复人"><a href="/i/sys/jump?un=nn6n" target="_blank">nn6n</a></span>
			<span class="threadlist_reply_date j_reply_data" title="发布时间">[field:pubdate function="MyDate('m-d',@me)"/]</span>
		</div>
	</div>
</div>
<div class="clear"></div>
</li>