<?php
$z[0]=Array("click","",116,130);
$z[1]=Array("click","",174,188);
$z[2]=Array("arcurl","",363,378);
$z[3]=Array("title","",387,401);
$z[4]=Array("title","",420,434);
$z[5]=Array("writer","",552,567);
$z[6]=Array("description","",727,747);
$z[7]=Array("litpic","",864,879);
$z[8]=Array("litpic","",891,906);
$z[9]=Array("litpic","",915,930);
$z[10]=Array("pubdate","",1231,1276);
$z[10][4]['function']="MyDate('m-d',@me)";

?>