<ul class="p_author post_icon">
			<li class="icon">
			<div class="icon_relative" style="padding:4px;margin-top:2px;">			  				
			<img class="icon" src="[field:face/]" style="width:80px;height:80px" />
            </div>	
			</li>
			 <li class="d_name">[field:uname/]</li>
                         <li class="d_name"><a href='[field:spaceurl /]' class="username">查看详细资料</a></li>
                         <li class="d_name"><a href='[field:spaceurl /]&action=guestbook' class="username">发送留言</a></li>
                         <li><a href="[field:spaceurl /]&action=newfriend" class="useract-af">加为好友</a></li>
			 <li class="l_badge">
			 	<div class="p_badge"></div>
			 </li>
		</ul>